repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --builtin=clear,rare,en-GB_to_en-US
          # NED: NASA/IPAC Extragalactic Database.
          - --ignore-words-list=ned
        files: \.(md|py|rst)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - jsonschema
          - pyyaml
          - types-PyYAML
        args: [--config-file=pyproject.toml]
        files: ^src/cosmic_observables/

  - repo: local
    hooks:
      - id: sphinx-build
        name: sphinx-build
        entry: sphinx-build -W docs docs/_build/html
        language: python
        language_version: python3.11
        additional_dependencies:
          - sphinx
          - furo
          - myst-nb
          - sphinx-design
          - sphinx-copybutton
        files: ^docs/
        pass_filenames: false
